/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AppLink: (typeof import("./../components/AppLink/index.vue"))["default"];
    AppMain: (typeof import("./../layout/components/AppMain/index.vue"))["default"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCard: (typeof import("element-plus/es"))["ElCard"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    HelloWorld: (typeof import("./../components/HelloWorld.vue"))["default"];
    IEpInfoFilled: (typeof import("~icons/ep/info-filled"))["default"];
    IEpSuccessFilled: (typeof import("~icons/ep/success-filled"))["default"];
    IEpWarningFilled: (typeof import("~icons/ep/warning-filled"))["default"];
    IEpWarnTriangleFilled: (typeof import("~icons/ep/warn-triangle-filled"))["default"];
    LangSelect: (typeof import("./../components/LangSelect/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Settings: (typeof import("./../layout/components/Settings/index.vue"))["default"];
    Sidebar: (typeof import("./../layout/components/Sidebar/index.vue"))["default"];
    SideMenu: (typeof import("./../layout/components/Sidebar/components/SideMenu.vue"))["default"];
    SideMenuItem: (typeof import("./../layout/components/Sidebar/components/SideMenuItem.vue"))["default"];
    SideMenuItemTitle: (typeof import("./../layout/components/Sidebar/components/SideMenuItemTitle.vue"))["default"];
    SideMenuItemTop: (typeof import("./../layout/components/Sidebar/components/SideMenuItemTop.vue"))["default"];
    SvgIcon: (typeof import("./../components/SvgIcon/index.vue"))["default"];
  }
}
